theme: jekyll-theme-minimal
logo: Fig_5G.jpg

title: SEAMLESS-WAVE
description: SEAMLESS-WAVE is a developing “SoftwarE infrAstructure for Multi-purpose fLood modElling at variouS scaleS”, based on WAVElets and their versatile properties. The vision behind SEAMLESS-WAVE is to produce an intelligent and holistic modelling framework, which can drastically reduce iterations in building and testing for an optimal setting and controlling the propagation of numerical model-error and/or uncertainty from physical inputs.
