theme: jekyll-theme-minimal
title: SEAMLESS-WAVE-2D
description: SEAMLESS-WAVE-2D is an ongoing project to develop a SoftwarE infrAstructure for Multi-purpose fLood modElling at variouS scaleS. It is a developing two-dimensional (2D) model aimed to facilitate flood simulation over a range of scales for the mesh and domain-sizes in both deterministic and scholastic settings. The vision behind developing SEAMLESS-WAVE-2D is the profor duction of flood modelling framework within the themes of “automatism” and “holistisity” handling flood modelling applications.

  
