theme: jekyll-theme-minimal
logo: Fig_5G.jpg


title: SEAMLESS-WAVE



description: SEAMLESS-WAVE is an ongoing project to develop a SoftwarE infrAstructure for Multi-purpose fLood modElling at variouS scaleS. The vision behind developing SEAMLESS-WAVE is to facilitate flood simulation over a range of scales for the mesh, domain-sizes and uncertainty within the themes of “automatism” and “holistisity”, so as to handle real-world modelling applications with the least reliance on user iterations.

  
