theme: jekyll-theme-minimal
logo: Fig_5G.jpg


title: SEAMLESS-WAVE



description: SEAMLESS-WAVE is an ongoing project to develop a SoftwarE infrAstructure for Multi-purpose fLood modElling at variouS scaleS. SEAMLESS-WAVE adopts a WAVElet-based approach with a view to exploit wavelet properties to increase intelligence and holisticity in handling flood simulations over a range of scales for the mesh- and domain-sizes, and propagation of uncertainties. SEAMLESS-WAVE is therefore aimed to significantly reduce reliance on user iterations in handling the tasks associated with building and running a flood model for real-world applications.
